### ISSUE TITLE
1.0.0 rejected from Chrome Web Store

### ISSUE THREAD

**Issue by r7kamura** [r7kamura/amazon_url_shortener#15]
> デベロッパー様
> 
> デベロッパー様が最近提出されたアイテムが残念ながら却下されたことをお知らせいたします。詳しくは下記をご覧ください。
> 
> 
> アイテム名: Amazon URL Shortener
> 
> アイテム ID: bonkcfmjkpdnieejahndognlbogaikdg
> 
> 違反:
> 
> 権限の使用:
> 
> 違反の参照 ID: Purple Potassium
> 違反事項: 次の権限をリクエストしているが使用していない。
> history
> 修正方法: 上記の権限を削除します。
> プログラム ポリシーの関連セクション:
> 製品の機能またはサービスを実装するために必要最小限となる権限へのアクセスをリクエストします。まだ実装していないサービスまたは機能で使用する可能性がある権限を、将来に備える目的でリクエストしないでください。（詳細）
> 
> 
> 誤って処分が適用されたと思われる場合
> 
> こちらの サポートページ で違反の詳細を確認し、Google に連絡してください。
> 
> 
> 私たちは Chrome ウェブストア へのデベロッパー様の貢献を高く評価しており、デベロッパー様のアイテムが Google のポリシーを遵守するようになるためのお手伝いを喜んでいたします。
> 
> よろしくお願い申し上げます。
> 
> Chrome ウェブストア デベロッパー サポート
> 
> ------------------------------------------------------
> デベロッパー向け利用規約
> プログラム ポリシー
> ブランドの取り扱いガイドライン

**Comment by r7kamura** [comment]
So does this mean that history permission is not needed for use of `window.history.replaceState` ?

https://github.com/r7kamura/amazon_url_shortener/blob/fcc8c1d6617e1f1e1ba464a174dd65c1db3b1ae9/src/main.ts#L1-L3

**Comment by azu** [comment]
The `history` permission is for [chrome.history](https://developer.chrome.com/docs/extensions/reference/history/).
[History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) is a web api. It is not required any permission.

**Comment by r7kamura** [comment]
@azu Thanks 🥇

**Comment by r7kamura** [comment]
I submitted v1.1.1 to Chrome Web Store, no history permission version.
