### ISSUE TITLE
Feature request: Add in support for smile.amazon.com links

### ISSUE THREAD

**Issue by MardukNT** [r7kamura/amazon_url_shortener#17]
Hello r7kamura,
Would you kindly consider extending this functionality to also support **smile.amazon.com** url link shortening, please.

EG: Taking links like this one (**https://smile.amazon.com/10TB-Elements-Desktop-Drive-WDBWLG0100HBK-NESN/dp/B07G3QMPB5/?th=1**) and shortening it down to this (**https://smile.amazon.com/dp/B07G3QMPB5/**), would be fantastic.

Thank you in advance for creating this Chrome extension and for listening to my suggestion.

**Comment by r7kamura** [comment]
Thank you for creating the Issue.

I've made the changes to support smile.amazon.com at #18 and submitted a new version to the Chrome Web Store so you can try it out when it is released 👍

**Comment by r7kamura** [comment]
The new version is released at chrome web store 🎉 
https://chrome.google.com/webstore/detail/amazon-url-shortener/bonkcfmjkpdnieejahndognlbogaikdg

I'll close this issue, but if you have any problem about smile.amazon.com yet, please reopen it 👋

**Comment by MardukNT** [comment]
Came back to say new version (1.3.0) is working great!  Thank you for the quick update to a fine extension.
