### ISSUE TITLE
Feature request: Adding in support for smile.amazon.co.uk & smile.amazon.de

### ISSUE THREAD

**Issue by MardukNT** [r7kamura/amazon_url_shortener#19]
Hello r7kamura,
I recently discovered Amazon also offers their 'Smile' charity program outside the USA. 
So, would you kindly consider adding in support for **smile.amazon.co.uk** & **smile.amazon.de** URL shortening, please?

Thank you in advance!

--MardukNT

**Comment by r7kamura** [comment]
OK, I'll try to add them 👌

**Comment by r7kamura** [comment]
I've submitted the new version to chrome web store, so it'll be released in a couple days

**Comment by r7kamura** [comment]
The new version has released on chrome web store 🎉
